server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_user?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: admin
  application:
    name: userservice # user服务的服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos服务地址
      discovery:
        cluster-name: BJ # 集群属性
mybatis:
  type-aliases-package: com.xue.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.xue: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:  # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka
