server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_order?useUnicode=true&amp;characterEncoding=UTF-8;useSSL=false
    username: root
    password: adminuser
  application:
    name: orderservice
mybatis:
  type-aliases-package: com.xue.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.xue: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
eureka:
  client:
    service-url:  # eureka的地址信息
      defaultZone: http://127.0.0.1:10086/eureka

userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule  # 负载均衡规则

ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients: # 指定饥饿加载的服务名称
      - userservice

